### PR TITLE
Consuming PUT methods

### PR DESCRIPTION
**Pull request by Diegocortes15**

### CODE REVIEW

**Review by holgiosalos — COMMENTED** [review]
Why in this PR are also included changes that are part of the previous section of the workshop. The changes in `test/GithubApi.Repositories.test.js` should not be part of this PR, since they were already reviewed on #7

**Comment by Diegocortes15** [comment]
When I did ``` Squash and merge ``` and then change to main branch and finally I did pull, I noticed that this could have some conflicts with files that alredy existed, even in one case I had to download again some libraries that I already had in the last commit.

I this last commit I did not do changes in file ``` test/GithubApi.Repositories.test.js. ``` So I going to clone repository and trying to do a new commit.

Excuse me for inconvenience 😅

**Comment by Diegocortes15** [comment]
I'm not sure is will be better delete this branch and remake it avoiding touch old files or what can I do in this cases?

Sorry, I not pretty good working with github 😅

**Review by holgiosalos — COMMENTED** [review]
1. Make a backup of the `test/GithubApi.Put.test.js` file, and also the change over `test/GithubApi.Authentication.test.js`.
2. Close this PR, delete the branch on GitHub.
3. Delete the branch in your local
4. checkout to main
5. git pull
6. create new branch and paste the changes again from your backup

**Pull request closed without merging**
